server {
    listen 80;

    # Performance: Compressão Gzip para JS, CSS, JSON, SVG
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
    gzip_min_length 1000;

    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ^~ /auth/ {
        proxy_pass http://keycloak:8080/auth/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $http_x_forwarded_port;
    }

    location /api/v1/risk {
        proxy_pass http://risk-service:8000/api/v1/risk;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v1 {
        proxy_pass http://etrm-service:8080/api/v1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /hubs {
        proxy_pass http://etrm-service:8080/hubs;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
    }

    location ^~ /mf-portfolio/ {
        proxy_pass http://mf-portfolio:80/mf-portfolio/;
        proxy_set_header Host $http_host;
    }

    location ^~ /mf-operations/ {
        proxy_pass http://mf-operations:80/mf-operations/;
        proxy_set_header Host $http_host;
    }

    location ^~ /mf-pricing/ {
        proxy_pass http://mf-pricing:80/mf-pricing/;
        proxy_set_header Host $http_host;
    }

    location ^~ /mf-hydrology/ {
        proxy_pass http://mf-hydrology:80/mf-hydrology/;
        proxy_set_header Host $http_host;
    }
}
