// <auto-generated />
using System;
using EtrmService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EtrmService.Infrastructure.Migrations
{
    [DbContext(typeof(EtrmDbContext))]
    [Migration("20260826144326_AddPluviaEntities")]
    partial class AddPluviaEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EtrmService.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CounterpartyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("counterparty_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal?>("OptionPremium")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("option_premium");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<decimal?>("StrikePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("strike_price");

                    b.Property<int>("Submarket")
                        .HasColumnType("integer")
                        .HasColumnName("submarket");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("VolumeMwMed")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("volume_mw_med");

                    b.HasKey("Id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("EtrmService.Domain.Entities.HydrologicalResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Basin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("basin");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("Submarket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("submarket");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("target_date");

                    b.Property<decimal>("ValueMwMed")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value_mw_med");

                    b.Property<decimal>("ValuePercentageMlt")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value_percentage_mlt");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("hydrological_results", (string)null);
                });

            modelBuilder.Entity("EtrmService.Domain.Entities.ModelExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_type");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("model_executions", (string)null);
                });

            modelBuilder.Entity("EtrmService.Domain.Entities.PrecipitationScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("horizon_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reference_date");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.ToTable("precipitation_scenarios", (string)null);
                });

            modelBuilder.Entity("EtrmService.Domain.Entities.HydrologicalResult", b =>
                {
                    b.HasOne("EtrmService.Domain.Entities.ModelExecution", "Execution")
                        .WithMany("Results")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_execution_results");

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("EtrmService.Domain.Entities.ModelExecution", b =>
                {
                    b.HasOne("EtrmService.Domain.Entities.PrecipitationScenario", "Scenario")
                        .WithMany("Executions")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_precipitation_scenario_executions");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("EtrmService.Domain.Entities.ModelExecution", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("EtrmService.Domain.Entities.PrecipitationScenario", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
