apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: energysuite-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/EnergySuite/EnergySuite.git'
    targetRevision: HEAD
    path: infra/k8s/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: energysuite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
