apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: energysuite

resources:
  - namespace.yaml
  - configmaps/env-configmap.yaml
  - secrets/db-secrets.yaml
  - infra-services/postgres.yaml
  - infra-services/kafka.yaml
  - infra-services/keycloak.yaml
  - infra-services/tempo-observability.yaml
  - infra-services/headlamp.yaml
  - app-services/etrm-service.yaml
  - app-services/risk-service.yaml
  - app-services/app-shell.yaml
  - app-services/mf-pricing.yaml
  - app-services/mf-portfolio.yaml
  - app-services/mf-hydrology.yaml
  - app-services/mf-operations.yaml
  - app-services/federation-manifest-cm.yaml
