apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: energysuite

resources:
  - namespace.yaml
  - configmaps/env-configmap.yaml
  - configmaps/postgres-init-cm.yaml
  - secrets/db-secrets.yaml
  - infra-services/postgres.yaml
  - infra-services/kafka.yaml
  - infra-services/keycloak.yaml
  - infra-services/keycloak-redirect-middleware.yaml
  - infra-services/tempo-observability.yaml
  - infra-services/grafana.yaml
  - infra-services/minio.yaml
  - infra-services/mlflow.yaml
  - infra-services/airflow.yaml
  - infra-services/headlamp.yaml
  - infra-services/headlamp-ingress.yaml
  - app-services/etrm-service.yaml
  - app-services/risk-service.yaml
  - app-services/app-shell.yaml
  - app-services/mf-pricing.yaml
  - app-services/mf-portfolio.yaml
  - app-services/mf-hydrology.yaml
  - app-services/mf-operations.yaml
  - app-services/federation-manifest-cm.yaml
  - ingress.yaml
