apiVersion: v1
kind: ConfigMap
metadata:
  name: federation-manifest-cm
  namespace: energysuite
data:
  federation.manifest.json: |
    {
      "mf-portfolio": "http://192.168.0.180:32001/remoteEntry.json",
      "mf-operations": "http://192.168.0.180:32002/remoteEntry.json",
      "mf-pricing": "http://192.168.0.180:32003/remoteEntry.json",
      "mf-hydrology": "http://192.168.0.180:32004/remoteEntry.json"
    }
