apiVersion: v1
kind: ConfigMap
metadata:
  name: federation-manifest-cm
  namespace: energysuite
data:
  federation.manifest.json: |
    {
      "mf-portfolio": "/mf-portfolio/remoteEntry.json",
      "mf-operations": "/mf-operations/remoteEntry.json",
      "mf-pricing": "/mf-pricing/remoteEntry.json",
      "mf-hydrology": "/mf-hydrology/remoteEntry.json"
    }
