apiVersion: v1
kind: Secret
metadata:
  name: energysuite-secrets
  namespace: energysuite
type: Opaque
stringData:
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "rootpassword"
  POSTGRES_DB: "etrm_db"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadminpassword"
