apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-keycloak-root
  namespace: energysuite
spec:
  redirectRegex:
    regex: ^(https?://auth\.energysuite\.local)/?$
    replacement: ${1}/auth/
    permanent: false
