"""
Official Sector Parsers for ONS and CCEE energy files: DADVAZ, PREVS, VNA.
Supports SMAP, PREVIVAZ and hydrological simulation data formats.
"""

from typing import List, Dict, Any, Optional
import io
import datetime


def parse_dadvaz(content: str) -> List[Dict[str, Any]]:
    """
    Parses ONS DADVAZ file content (daily/monthly incremental streamflows).
    Format: Usina Code, Day/Month, Values for stations.
    """
    records = []
    lines = content.strip().splitlines()
    
    for line in lines:
        line = line.strip()
        if not line or line.startswith("&") or line.startswith("#") or line.startswith("DADVAZ"):
            continue
        
        parts = line.split()
        if len(parts) >= 3:
            try:
                usina_id = int(parts[0])
                time_step = parts[1]
                flow_value = float(parts[2].replace(",", "."))
                
                records.append({
                    "usina_id": usina_id,
                    "time_step": time_step,
                    "flow_m3s": flow_value
                })
            except (ValueError, IndexError):
                continue
                
    return records


def generate_dadvaz(records: List[Dict[str, Any]]) -> str:
    """
    Generates ONS DADVAZ format file from structured hydrological records.
    """
    output = io.StringIO()
    output.write("& ARQUIVO DADVAZ GERADO PELO ENERGYSUITE PLUVIA SERVICE\n")
    output.write("& USINA   POSTO   VAZAO_M3S\n")
    
    for rec in records:
        usina_id = rec.get("usina_id", 1)
        time_step = rec.get("time_step", "1")
        flow = rec.get("flow_m3s", 0.0)
        output.write(f"{usina_id:>5}  {time_step:>6}  {flow:>10.2f}\n")
        
    return output.getvalue()


def parse_prevs(content: str) -> List[Dict[str, Any]]:
    """
    Parses PREVS (PREVIVAZ forecasting model output files).
    """
    results = []
    lines = content.strip().splitlines()
    
    current_posto = None
    for line in lines:
        line = line.strip()
        if not line or line.startswith("&") or line.startswith("#"):
            continue
            
        if line.startswith("POSTO"):
            parts = line.split()
            if len(parts) >= 2:
                current_posto = int(parts[1])
            continue
            
        parts = line.split()
        if len(parts) >= 2 and current_posto is not None:
            try:
                week_or_month = parts[0]
                ena_value = float(parts[1].replace(",", "."))
                results.append({
                    "posto_id": current_posto,
                    "period": week_or_month,
                    "ena_mwmed": ena_value
                })
            except (ValueError, IndexError):
                continue
                
    return results


def generate_prevs(records: List[Dict[str, Any]]) -> str:
    """
    Generates PREVS format file for PREVIVAZ forecasting model.
    """
    output = io.StringIO()
    output.write("& ARQUIVO PREVS - PREVIVAZ - GENERATED BY ENERGYSUITE\n")
    
    grouped: Dict[int, List[Dict[str, Any]]] = {}
    for r in records:
        posto = r.get("posto_id", 1)
        if posto not in grouped:
            grouped[posto] = []
        grouped[posto].append(r)
        
    for posto, items in grouped.items():
        output.write(f"POSTO {posto}\n")
        for item in items:
            period = item.get("period", "SEM-1")
            val = item.get("ena_mwmed", 0.0)
            output.write(f"  {period:<8} {val:>10.2f}\n")
            
    return output.getvalue()


def parse_vna(content: str) -> List[Dict[str, Any]]:
    """
    Parses VNA (Valor Nominal Atualizado - NTN-B / IPCA inflation indices for financial contracts).
    """
    vna_data = []
    lines = content.strip().splitlines()
    
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#") or line.startswith(";"):
            continue
            
        parts = line.split()
        if len(parts) >= 2:
            try:
                date_str = parts[0]
                vna_val = float(parts[1].replace(",", "."))
                vna_data.append({
                    "date": date_str,
                    "vna_value": vna_val
                })
            except (ValueError, IndexError):
                continue
                
    return vna_data


def generate_vna(records: List[Dict[str, Any]]) -> str:
    """
    Generates VNA file content.
    """
    output = io.StringIO()
    output.write("# TABELA DE VNA - VALOR NOMINAL ATUALIZADO (CCEE/BCB)\n")
    for r in records:
        dt = r.get("date", datetime.date.today().isoformat())
        val = r.get("vna_value", 4000.0)
        output.write(f"{dt}  {val:.6f}\n")
    return output.getvalue()
